# Generated by Django 4.1.2 on 2022-10-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diligencia',
            options={'verbose_name': 'Diligência', 'verbose_name_plural': 'Diligencias'},
        ),
    ]
