# Generated by Django 4.1.2 on 2022-10-15 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diligencias', '0002_alter_diligencia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diligencia',
            options={'verbose_name': 'Diligência', 'verbose_name_plural': 'Diligências'},
        ),
    ]
